  # Resmi OpenJDK Docker görüntüsünü kullan

   FROM openjdk:14

     

     # Uygulamanın çalıştırılacağı dizini oluştur

     WORKDIR /app

     

     # Uygulama JAR dosyasını kopyala

     COPY target/EurekaServer-1.jar .

     

     # Uygulamayı başlat

     CMD ["java", "-jar", "EurekaServer-1.jar"]
